### ISSUE TITLE
How to play an xm file?

### ISSUE THREAD

**Issue by CocosGames** [dapetcu21/defold-fmod#29]
Could fmod play an xm file as a background music with / without banks?

**Comment by dapetcu21** [comment]
No idea. Check the [FMOD docs](https://www.fmod.com/resources/documentation-api?version=2.1&page=welcome.html) for that. I expose most of the Core and Studio APIs. Prolly you should look in the Core API.

**Comment by CocosGames** [comment]
The doc shows:
system.createSound() & system.playSound() are the functions.
But I don't know how to use them. ERROR:SCRIPT: An invalid parameter was passed to this function.

**Comment by dapetcu21** [comment]
fmod.system.create_sound()

**Comment by CocosGames** [comment]
The doc is based on C language, is there any API based on Lua?

**Comment by dapetcu21** [comment]
Most of the C APIs are mirrored in Lua automatically. So, if something exists in C, it most likely also exists in Lua.

The mapping rules are here: https://github.com/dapetcu21/defold-fmod#usage

The `mode` argument is an enum, so `fmod.DEFAULT`, `fmod.CREATESTREAM` etc.

You might get away with passing nil for the `FMOD_CREATESOUNDEXINFO` structure, but otherwise, you can create one with `fmod.FMOD_CREATESOUNDEXINFO()` and then populate its fields like you would a Lua table. Not sure how to go about `cbsize` though, since `sizeof FMOD_CREATESOUNDEXINFO` is not exposed anywhere to Lua, so that's a good candidate for a PR, yes.

The final `FMOD::Sound **sound` argument is not necessary as that's an output value and you'll get it as the first return value of `fmod.system.create_sound()`.

**Comment by CocosGames** [comment]
Difficult to use, turn to xm player, thanks anyway.
