### ISSUE TITLE
Readme should mention including the path to the banks in game.project custom_resources if banks are being used

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#7]

**Comment by dapetcu21** [comment]
Fair enough. This could be clearer. Albeit, you don't necessarily need to put them in custom resources. It's actually better to put them in `bundled_resources` and use `load_bank_file`. That might not work when running in the editor, but it has the benefit that a full copy of the banks is not stored in memory and they can be streamed from disk.

The way I approach it in Interrogation is that I put the banks in `bundled_resources` when doing the final builds and otherwise use them from `bundled_resources` when running in the editor.

**Comment by subsoap** [comment]
Those kind of tips would be helpful to have in the readme too!

I am first trying to just play a music track... so those would be best to be streamed for sure.

But maybe some kind of sound effects you would want to have in memory all of the time if they are played often?

**Comment by subsoap** [comment]
I ended up using

![bundle](https://user-images.githubusercontent.com/409170/48456440-f9066000-e773-11e8-80f7-c1091b63fc12.png)

With

```
		fmod.studio.system:load_bank_file("./_assets/_fmod_banks/master.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
		fmod.studio.system:load_bank_file("./_assets/_fmod_banks/master.strings.bank", fmod.STUDIO_LOAD_BANK_NORMAL)
```

Then I have a symlink copy from the root folder to the bundle folder.

**Comment by dapetcu21** [comment]
I added a README section about loading banks
